# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-07 02:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sfs_site', '0002_auto_20170107_0238'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
